Improve libp2p: Connections and Users
protocol/launchpad pull request #154
Opened 2022-06-29 18:43 UTC by enolal826

2022-06-30 17:33 UTC, MarcoPolo requested changes

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +hash function code is the _identity code_. The identity code means that no has been applied to the digest.
```suggestion
hash function code is the _identity hash_. The identity hash means the output digest is the same as the input.
```

And maybe link to multihashes?

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +![How peer IDs are generated](<../../.gitbook/assets/libp2p-peer-identity.png>)
It's base58 encoded: https://github.com/libp2p/go-libp2p-core/blob/master/peer/peer.go#L161

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +A multiaddress allows you to specify the transport for the connection (TCP, UDP, QUIC...) and network to establish that connection (IP, DNS...).
DNS isn't really a network, right?

Maybe this should say something like:
```suggestion
A multiaddress allows you to specify the transport for the connection (TCP, UDP, QUIC...) and how to reach the node to establish the connection (IP, DNS...).
```

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +/ip4/127.0.0.1/udp/1234
Prefer a tcp example since we don't (afaik) have a udp only transport.

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +The handshake starts the connection with the peer and verifies that the peer can understand the `multistream-set` protocol.
```suggestion
The handshake starts the connection with the peer and verifies that the peer can understand the `multistream-select` protocol.
```

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +The handshake starts the connection with the peer and verifies that the peer can understand the `multistream-set` protocol.
also link to multstream protocol repo

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +> multistream 1.0.0
See: https://github.com/multiformats/multistream-select#protocol

Use `/multistream/1.0.0`

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +> multistream 1.0.0
do you mean to put tls in here?

also prefer the path form `/<proto>/<version>`

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +Once the connection is secured, a multiplexer protocol is negotiated. Muxtiplexing means allowing several protocols through a single connection. For example, if your peer wants to consume both TCP an
> if your peer wants to consume both TCP and UDP, the same connection will be used

This doesn't make sense. TCP and UDP are the way we send bytes around, not the thing that users would interact with.

This should probably say something like:
`If you want to open up multiple distinct logical streams to a peer we can multiplex those streams on a signle connection. For example you may want to interact with a peer on the DHT, but you may also want to `ping` that peer. Multiplexing lets you do both of these on the same underlying connection.

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +![Streams in a single connection](<../../.gitbook/assets/libp2p-streams.png>)
This image also doesn't make sense for the reason I stated above. It would make sense if these were protocols like kad-dht, identify, bitswap, etc...

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +After the connection is established (i.e. handshake, security, and multiplexing), peers exchange what protocols they support. The Multistream protocol is used to ask for a list of supported protocols
Peers exchange what protocols they support with identify. I'm not sure multistream ls is still used (but I could be wrong)

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +By default, this is done after the connection is established, but the Multistream list function can be used later to verify if new protocols have been added.
Prefer to use identifyPush or identify delta.

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +Every supported protocol is assigned a handler function, which manages the data for that protocol.
```suggestion
Every supported protocol is assigned a handler, which manages the data for that protocol.
```

May not be a function. In the case of go-libp2p it is, but rust-libp2p they are objects that implement a trait. So function is more a implementation level detail.

2022-06-30 17:33 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +The Advertiser offers services to the network, which means that shares the protocols that it supports with the rest of the network. On the other hand, the Discoverer is able to find peers.
```suggestion
The Advertiser offers services to the network, which means that shares the protocols that it supports with the rest of the network. The Discoverer is able to find peers.
```

Since you aren't contrasting these things. You're just stating two things.

2022-07-07 20:51 UTC, MarcoPolo requested changes

2022-07-07 20:51 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +For example, in the following snippet, `libp2p-go` (the Go implementation of libp2p), is used to create a node with default settings.
```suggestion
For example, in the following snippet, `go-libp2p` (the Go implementation of libp2p), is used to create a node with default settings.
```

2022-07-07 20:51 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +After the connection is established (i.e. handshake, security, and multiplexing), peers exchange what application protocols they support. Because `multistream-select` is used, the procedure to agree
```suggestion
After the connection is established (i.e. handshake, security, and multiplexing), peers exchange what application protocols they support. Because `multistream-select` is used, the procedure to agree on an application protocol is the same as for the security and mutiplexing negotiations: the protocol identifier is sent to the peer and `na` is answered if the protocol is not supported.
```

2022-07-07 20:51 UTC, MarcoPolo commented on docs/libp2p/libp2p-connections-users.md
> +The Advertiser offers services to the network, which means that shares the protocols that it supports with the rest of the network. The Discoverer is able to find peers.
```suggestion
The Advertiser offers services to the network, which means that it shares the protocols that it supports with the rest of the network. The Discoverer is able to find peers.
```

2022-07-07 21:25 UTC, walkerlj0 approved these changes
If the case is that is is supposed to be >58 bytes in length, don't forget to update diagram!

2022-07-08 11:40 UTC, enolal826 commented on docs/libp2p/libp2p-connections-users.md
> +![How peer IDs are generated](<../../.gitbook/assets/libp2p-peer-identity.png>)
No, the encoding occurs after the multihash is generated. The order is:
1. Identify if your public key > 42 bytes
2. Generate the multihash (which is different depending on the public key's length)
3. Encode the multihash (base58 encode), regardless of the length

2022-07-08 17:42 UTC, walkerlj0 commented on docs/libp2p/libp2p-connections-users.md
> +{% tabs %}
```suggestion
{% tabs %}
{% tab title="JS" %}
```javascript
import * as IPFS from 'ipfs-core'

const ipfs = await IPFS.create()
const { cid } = await ipfs.add('Hello world')
console.info(cid)
```
{% endtab %}
```

2022-07-08 18:01 UTC, walkerlj0 approved these changes

2022-07-08 18:03 UTC, merged