Improve libp2p: DHT section
protocol/launchpad pull request #163
Opened 2022-07-06 17:10 UTC by enolal826

2022-07-12 16:22 UTC, hsanjuan requested changes

2022-07-12 16:22 UTC, hsanjuan commented on docs/libp2p/libp2p-dht.md
> +Every peer holds a list of peer IDs that are _close_. The closeness of two peers is defined by the distance function (i.e. `distance(peer1, peer2)`), in the same way as the distance between a peer an
It seems docs below assume the node is just storing "close" nodes, but the reality is it stores close and not so close nodes.

2022-07-12 16:22 UTC, hsanjuan commented on docs/libp2p/libp2p-dht.md
> +3. The `key -> value` record is stored in every node returned by the `FIND_NODE` operation.
I'm not sure this is like this. I think it probably looks more like the Value Retrieval part.

That is, FIND_NODE will return some peers, and than then you are supposed to run FIND_NODE on those peers until you arrive to peers that are close-enough to the key. Only those will accept storing the key.

2022-07-12 16:22 UTC, hsanjuan commented on docs/libp2p/libp2p-dht.md
> +2. From `Peer 1`, a `FINDE_NODE(key1)` request is sent to the close nodes of `Peer 2` and `Peer 3` (i.e. `Peer 5`, `Peer 6`, `Peer 7`, `Peer 8`).
```suggestion
2. From `Peer 1`, a `FIND_NODE(key1)` request is sent to the close nodes of `Peer 2` and `Peer 3` (i.e. `Peer 5`, `Peer 6`, `Peer 7`, `Peer 8`).
```

2022-08-01 20:36 UTC, walkerlj0 reviewed
Looks good-- We will have to decide further on where we want to cover DHT (and to what depth in what section) but this is amazing content!

2022-08-02 08:55 UTC, merged