Improvement libp2p: Circuit Relays and Pubsub
protocol/launchpad pull request #167
Opened 2022-07-11 17:29 UTC by enolal826

2022-07-11 21:36 UTC, MarcoPolo requested changes

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +To solve this issue, libp2p provides a protocol called _circuit-p2p_. When a peer is not reachable by other peers, another machine listens for connections on its behalf. Then, those connections are f
```suggestion
To solve this issue, libp2p provides a protocol called [Circuit Relay v2](https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md). When a peer is not reachable by other peers, another machine can relay messages for that peer. Consider the following diagram:
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +![Curcuit relay example](<../../.gitbook/assets/libp2p-circuit-relay.png>)
```suggestion
![Circuit relay example](<../../.gitbook/assets/libp2p-circuit-relay.png>)
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +3. `C` forwards messages from `B` to `A`.
```suggestion
3. `C` relays messages from `B` to `A`.
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +1. `A` is not reachable, so it asks `C` to listen for connections on its behalf.
```suggestion
1. `A` is not reachable, so it asks `C` to listen on its behalf.
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +2. `B` establishes a connection to `C`.
```suggestion
2. `B` establishes a connection to `C` in an attempt to communicate with `A`.
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +Currently, there are two different version of the circuit relay protocol in libp2p: [circuit-v1](https://github.com/libp2p/specs/blob/master/relay/circuit-v1.md) and [circuit-v2](https://github.com/l
v1 is deprecated, let's only mention v2

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +You can get more information about circuit relays in the [libp2p documentation](https://docs.libp2p.io/concepts/circuit-relay/).
Probably better to point to the specs here.

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +In Floosub, the first implementation of the pub/sub protocol, messages are delivered to all the nodes of a peer. For example, consider the following diagram.
```suggestion
In Floosub, the first implementation of the pub/sub protocol, messages are delivered to all the connected nodes of a peer. For example, consider the following diagram.
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +The main problem of FloodSub is that it duplicates messages, thus using a lot of bandwidth. In the previous example, `Peer 4` receives the message twice.
It would be great to lead with some advantages of floodsub, namely censorship resistance. What do you think about:

```suggestion
FloodSub is simple, reliable, and highly resistant to malicious actors and censors, but the main problem of FloodSub is that it duplicates messages, thus using a lot of bandwidth. In the previous example, `Peer 4` receives the message twice.
```

2022-07-11 21:36 UTC, MarcoPolo commented on docs/libp2p/distributed-networking-solutions.md
> +Gossipsub, the protocol developed after FloodSub, tries to reduce the number of duplicate messages (i.e., bandwidth) by taking a different approach. Gossipsub is covered later in the Launchpad curric
Generally it helps to have links to more resources where one could learn even more. e.g.
```suggestion
[Gossipsub](https://arxiv.org/pdf/2007.02754.pdf), the protocol developed after FloodSub, tries to reduce the number of duplicate messages (i.e., bandwidth) by taking a different approach. Gossipsub is covered later in the Launchpad curriculum.
```

2022-07-13 17:12 UTC, mrodriguez3313 commented on docs/libp2p/distributed-networking-solutions.md
> +In Floosub, the first implementation of the pub/sub protocol, messages are delivered to all the connected nodes of a peer. For example, consider the following diagram.
```suggestion
In Floodsub, the first implementation of the pub/sub protocol, messages are delivered to all the connected nodes of a peer. For example, consider the following diagram.
```

2022-07-13 17:22 UTC, mrodriguez3313 approved these changes
Looks good. I made some spelling edits.

2022-08-02 09:03 UTC, merged