Initial PLN objectives and quiz changes
protocol/launchpad pull request #285
Opened 2022-09-27 20:03 UTC by daveo101

2022-09-28 20:25 UTC, daveo101 commented
Not sure why the image won't load. It appears a previous image was coded but also didn't appear on live page.

2022-09-29 16:26 UTC, mrodriguez3313 commented
> Not sure why the image won't load. It appears a previous image was coded but also didn't appear on live page. 

No worries! For images to render like this you have to have the image and file that is referencing it in their own directory.

So what you need to do is make a new folder called (arbitrarily) "objectives". Then you need to move your file called "introduction" into it, but you HAVE to rename it to "index.md". Finally you have to move the image into the same directory and it will be able to render on the page.

2022-09-29 20:29 UTC, daveo101 commented
Hm... Tried that but still no luck. Also, now if I make any change on VS code it doesn't change on my localhost. Could that be due to moving and renaming the .md file?

2022-09-30 14:27 UTC, walkerlj0 requested changes
Hey, the quiz linked is still named 'PLN post-test' Change the name to PLN Quiz, and put all questions on to just one page, shouldn't be a two part thing!

2022-10-02 19:47 UTC, mrodriguez3313 requested changes

2022-10-02 19:47 UTC, mrodriguez3313 commented on content/en/curriculum/pln/pln-resources.md
> +Take the [**PLN Quiz**](https://docs.google.com/forms/d/e/1FAIpQLSfin7rDiiBqV9ybs1gV-n4hEv4bXmhanmf13Czd_zvDEHIsLw/viewform?usp=sf_link) after covering the pre-requisite content to gauge your underst
I dont like the word pre-requisite here It makes it seem like they need to go through the "prerequisite" section of the curriculum as opposed to the stuff in this module. I would change it to be something like 
```suggestion
Take the [**PLN Quiz**](https://docs.google.com/forms/d/e/1FAIpQLSfin7rDiiBqV9ybs1gV-n4hEv4bXmhanmf13Czd_zvDEHIsLw/viewform?usp=sf_link) after covering the PLN module to gauge your understanding.
```

2022-10-03 16:14 UTC, merged