Moved around content. Added goals. Added own content and descriptions.
protocol/launchpad pull request #333
Opened 2022-11-08 00:27 UTC by mrodriguez3313

- Added gateway goals to json
- I moved content around in the original Gateway page
- I moved DNSlink info that was commented out from ipfs1.2 changes into gateways instead. This is relevant here because you use the [path-gateway URL schema](https://curriculum.pl-launchpad.io/curriculum/ipfs/ipfs-gateways/#path-gateway) to access data from DNSLink. And implementors may need this to create their own gateways. 
- I cut out large portions of the [current projects](https://curriculum.pl-launchpad.io/curriculum/ipfs/ipfs-gateways/#current-projects-1) section to link to their respective articles instead. Shortening this page by over 30 lines, all while adding in more relevant content.

2022-11-09 22:12 UTC, walkerlj0 requested changes

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +- a domain name you control
```suggestion
- A domain name you control (e.g. `www.me.com`)
```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +- A CID or an IPNS name to link to
```suggestion
- A CID or an IPNS name to link to, such as a website published with [Fleek.co](https://fleek.co/)
```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +### Collaborations
```suggestion
## Collaborations
```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  ### IPFS and the JavaScript ecosystem
```suggestion
### IPFS and JavaScript
```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  ### IPFS Companion browser extension
```suggestion
### IPFS Companion Browser Extension
```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  #### Brave
```suggestion

```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  #### Brave
Moving this up

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  #### Opera
```suggestion

```

2022-11-09 22:12 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
>  #### Opera
Moved up

2022-11-09 22:44 UTC, mrodriguez3313 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +> **Native URI requires the CID to be case-insensitive. Use of CIDv1 in Base32 is advised.**
@walkerlj0 Can you point me to the source for CIDv2? or did you mean CIDv0?

2022-11-09 22:44 UTC, mrodriguez3313 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +When [origin-based security](https://en.wikipedia.org/wiki/Same-origin_policy) is needed, CIDv1's case-insensitive encoding should be used in the subdomain:
This whole page is a deep page. See line 11. Would you prefer we give the deep residents less technical things to read through on this page then?

2022-11-10 15:43 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +> **Native URI requires the CID to be case-insensitive. Use of CIDv1 in Base32 is advised.**
I meant CIDv0, sorry! updated the suggestion

2022-11-10 15:46 UTC, walkerlj0 commented on content/en/curriculum/ipfs/ipfs-gateways.md
> +When [origin-based security](https://en.wikipedia.org/wiki/Same-origin_policy) is needed, CIDv1's case-insensitive encoding should be used in the subdomain:
I just think this part is unecessary, we can cut it, and just add something like 'learn more about read more about locators requiring origin-based security'

2022-11-10 23:22 UTC, walkerlj0 commented on config/_default/goals.json
> +          "description": "Learn about current public Gateways and how any node in the network can become one"
```suggestion
          "description": "Learn about current public Gateways and how any node in the network can provide this service"
```

2022-11-11 00:16 UTC, walkerlj0 commented on config/_default/goals.json
> +      "description": "Learn about IPFS Gateways and how they bridge web2 and web3",
```suggestion
      "description": "Learn about IPFS Gateways and how they help bridge information between web2 and web3",
```

2022-11-11 22:25 UTC, merged