libp2p updates:  1.2 goal
protocol/launchpad pull request #336
Opened 2022-11-10 13:51 UTC by enoldev

2022-11-12 00:08 UTC, mrodriguez3313 requested changes
10 minor spelling and sentence changes.

2022-11-12 00:08 UTC, mrodriguez3313 commented on content/en/curriculum/libp2p/core-concepts/index.md
> +The router is connected to the Internet, and is assigned a public IP address. Three devices are connected to the route, which manages the incoming and outgoing data.
```suggestion
The router is connected to the Internet, and is assigned a public IP address. Three devices are connected to the router, which manages the incoming and outgoing data.
```

2022-11-12 00:08 UTC, mrodriguez3313 commented on content/en/curriculum/libp2p/core-concepts/index.md
> +Although this is a valid system, you have to infer some data: what protocol is behind `127.0.0.1`? or what protocol is behind `8080`?
```suggestion
Although this is a valid system, you have to infer some data about what protocol is behind `127.0.0.1`? And what protocol is behind `8080`?
```

2022-11-12 00:08 UTC, mrodriguez3313 commented on content/en/curriculum/libp2p/core-concepts/index.md
> +To receive messages, peers subscribe to topics they are interested in. Peer only receive messages from topics they are subscribed to.
```suggestion
To receive messages, peers subscribe to topics they are interested in. Peer only receive messages from topics they are subscribed to.
```
```suggestion
To receive messages, peers subscribe to topics they are interested in.
```

2022-11-21 10:15 UTC, enoldev commented
@mrodriguez3313 About the capitalization of "libp2p", I was told it should be lowercase (probably marketing and brand), but you can bring it up in the content stand-up to see what's our standard

2022-11-21 12:14 UTC, enoldev commented
Merging to use this content in upcoming libp2p updates PRs

2022-11-21 12:14 UTC, merged