First version of Tutorials page
protocol/launchpad pull request #413
Opened 2022-12-05 13:18 UTC by enoldev

2022-12-06 18:04 UTC, walkerlj0 commented
To Dos before merging
- [ ] Remove icons from top bar
- [ ] Create a redirect from `https://curriculum.pl-launchpad.io/about` -> `https://curriculum.pl-launchpad.io/resources/about`
- [ ] Merge lindsz/tutorials-page into enol/tutorials-page
- [ ] Link 'About' page in footer of site

2022-12-06 19:22 UTC, walkerlj0 requested changes
See comment!

2022-12-09 19:25 UTC, mrodriguez3313 approved these changes

2022-12-13 16:54 UTC, walkerlj0 approved these changes

2022-12-14 11:13 UTC, merged