Pln1.1
protocol/launchpad pull request #468
Opened 2023-01-13 20:08 UTC by Wu-Ca

Updated PLN 1.1 content.

2023-01-13 20:13 UTC, walkerlj0 commented
@Wu-Ca I made a couple edits (review not complete yet)

2023-01-13 20:15 UTC, walkerlj0 requested changes
Have some change requests

2023-01-13 20:15 UTC, walkerlj0 commented on content/en/curriculum/pln/intro-to-pl/index.md
> +Protocol Labs is building the next generation of the internet. We are an open-source Network that spans the research-to-development pipeline to create new protocols, tools, and services to improve th
```suggestion
Protocol Labs is building the next generation of the internet. We are an open-source network that spans the research-to-development pipeline to create new protocols, tools, and services to improve the internet radically. Our products serve thousands of organizations and millions of people.
```

2023-01-13 20:15 UTC, walkerlj0 commented on content/en/curriculum/pln/intro-to-pl/index.md
> +Many teams in the PL Network are fully distributed and follow a standard set of open-source practices to grow and flourish together. This distributed, open-source philosophy is at the core of how PL
Add a link here to the network directory at: https://www.plnetwork.io/directory/teams

2023-01-13 20:18 UTC, Wu-Ca commented on content/en/curriculum/pln/intro-to-pl/index.md
> +Many teams in the PL Network are fully distributed and follow a standard set of open-source practices to grow and flourish together. This distributed, open-source philosophy is at the core of how PL
```suggestion
Many [teams in the PL Network](https://www.plnetwork.io/directory/teams)  are fully distributed and follow a standard set of open-source practices to grow and flourish together. This distributed, open-source philosophy is at the core of how PL operates.
```

2023-01-19 20:21 UTC, walkerlj0 commented
Will re-do this PR

2023-01-19 20:21 UTC, closed without merging