Added sections at the bottom
protocol/launchpad pull request #488
Opened 2023-01-27 17:36 UTC by walkerlj0

2023-01-29 08:13 UTC, mrodriguez3313 requested changes

2023-01-29 08:13 UTC, mrodriguez3313 commented on content/en/curriculum/dev-tools/bacalhau/index.md
> +* **Option 1 –** [Install Bacalhau](https://docs.bacalhau.org/getting-started/installation/#installing-the-bacalhau-cli-locally) on your local machine and Install [Python](https://www.python.org/down
```suggestion
* **Option 1 –** [Install Bacalhau](https://docs.bacalhau.org/getting-started/installation/#installing-the-bacalhau-cli-locally) on your local machine and install [Python](https://www.python.org/downloads/) & [Pip](https://pip.pypa.io/en/stable/installation/)
```

2023-01-29 08:13 UTC, mrodriguez3313 commented on content/en/curriculum/dev-tools/bacalhau/index.md
> +* **Option 3 –** Run Bacalhau in [Gitpod](https://gitpod.io/#https://github.com/protocol/launchpad-tutorials) in a web browser
idk if this link works can you double check it? I wasn't able to get anything to load

2023-01-29 08:13 UTC, mrodriguez3313 commented on content/en/curriculum/dev-tools/bacalhau/index.md
> +* [Running Oandas in Bacalhau](https://docs.bacalhau.org/examples/workload-onboarding/python-pandas/) – In this tutorial, you will deploy a Python script on Bacalhau. The script a basic application t
```suggestion
* [Running Pandas in Bacalhau](https://docs.bacalhau.org/examples/workload-onboarding/python-pandas/) – In this tutorial, you will deploy a Python script on Bacalhau. The script a basic application that uses the Pandas Python library
```

2023-01-30 10:33 UTC, enoldev commented on content/en/curriculum/dev-tools/bacalhau/index.md
> +* **Option 3 –** Run Bacalhau in [Gitpod](https://gitpod.io/#https://github.com/protocol/launchpad-tutorials) in a web browser
It works for me, it should bring you to Gitpod, where you have to log in

2023-01-30 16:53 UTC, walkerlj0 commented
Done in another PR

2023-01-30 16:53 UTC, closed without merging