Updating Dev Tools Landing Page
protocol/launchpad pull request #489
Opened 2023-01-27 19:37 UTC by walkerlj0

2023-01-29 08:09 UTC, mrodriguez3313 requested changes
small edits

2023-01-29 08:09 UTC, mrodriguez3313 commented on content/en/curriculum/dev-tools/objectives/index.md
> +All of these projects are a part of the Protocol Labs Network and an important part of our ecosystem and tooling, providing important solutions for the technology across the Protocol Labs stack, whet
```suggestion
All of these projects are a part of the Protocol Labs Network and an important part of our ecosystem and tooling, providing important solutions for the technology across the Protocol Labs stack, whether they are Open Source Software (OSS), protocols, or tools and services that are a part of the ecosystem of companies and projects that are working together to power the distributed web.
```

2023-01-29 08:09 UTC, mrodriguez3313 commented on content/en/curriculum/dev-tools/objectives/index.md
> +* **[Web3.storage](/curriculum/dev-tools/web3-storage/)**: A pinning service for Filecoin & IPFS storage
Web3.storage is on here twice
```suggestion
```

2023-01-30 16:07 UTC, enoldev approved these changes

2023-01-30 16:52 UTC, merged